tasks:
  - init: sudo apt-get install -y openjdk-21-jdk
    command: |
      sudo update-alternatives --install /usr/bin/java java /usr/lib/jvm/java-21-openjdk-amd64/bin/java 1
      sudo update-alternatives --config java
      ./mvnw install -DskipTests=false
