# .gitpod.yml
tasks:
  - init: |
      sudo apt-get update --fix-missing
      sudo apt-get install -y openjdk-21-jdk docker-compose
      sudo update-alternatives --set java /usr/lib/jvm/java-21-openjdk-amd64/bin/java
      echo 'export JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64' >> ~/.bashrc
      echo 'export PATH=$JAVA_HOME/bin:$PATH' >> ~/.bashrc
      source ~/.bashrc
  - command: |
      # Certifique-se de que o Java 21 está no PATH
      export JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64
      export PATH=$JAVA_HOME/bin:$PATH
      ./mvnw clean install -DskipTests=false
      docker-compose up --build
