services:
  account-database:
    container_name: jupyter
    image: mysql:latest
    environment:
      MYSQL_DATABASE: account
      MYSQL_ROOT_PASSWORD: abc123
    ports:
      - 3306:3306
    networks:
      - account-private-network

  spring-boot-api:
    container_name: spring-boot-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - account-private-network
    depends_on:
      - account-database

networks:
  account-private-network:
    name: account-private-network
    driver: bridge