services:
  account-database:
    container_name: Thurinblalas
    image: mysql:latest
    environment:
      MYSQL_DATABASE: account
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: abc123
    ports:
      - 3306:3306
    networks:
      - account-private-network

  account-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: account-api
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      MYSQL_HOST: account-database
      MYSQL_PORT: 3306
      MYSQL_DATABASE: account
      MYSQL_USER: root
      MYSQL_PASSWORD: abc123
    depends_on:
      - account-database
    networks:
      - account-private-network

networks:
  account-private-network:
    name: account-private-network
    driver: bridge
